before_script:
  - chmod +x ./gradlew
  - export ANDROID_HOME=/android_sdk
  - export ANDROID_SDK_ROOT=/android_sdk

stages:
  - check
  - test
  - build
  - upload_to_bintray

lint_job:
  stage: check
  script:
    - ./gradlew lint
  except:
    - tags

ktlint_job:
  stage: check
  script:
    - ./gradlew ktlintCheck
  except:
    - tags

detekt_job:
  stage: check
  script:
    - ./gradlew detekt
  except:
    - tags

test_job:
  stage: test
  script:
    - ./gradlew testDebugUnitTest
  except:
    - tags

debug_build_job:
  stage: build
  script:
    - bundle exec fastlane debug_build
  except:
    - tags
    - develop

qa_build_job:
  stage: build
  script:
    - bundle exec fastlane qa_build
  only:
    - develop
  except:
    - tags

upload_to_bintray_job:
  stage: upload_to_bintray
  script:
    - bundle exec fastlane upload_to_bintray
  only:
    - master
  except:
    - tags